# Generated by Django 4.2 on 2023-05-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='code',
            new_name='id',
        ),
    ]
