# Generated by Django 4.2 on 2023-05-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='app_number',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='service',
        ),
    ]
