# Generated by Django 4.2 on 2023-05-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='color',
        ),
        migrations.AddField(
            model_name='auto',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('A1', 'A1'), ('B', 'B'), ('B1', 'B1'), ('C', 'C'), ('C1', 'C1')], default='A1', max_length=2, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='auto',
            name='grnz',
            field=models.CharField(default=None, max_length=8, verbose_name='ГРНЗ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Исправен'),
        ),
        migrations.AlterField(
            model_name='department',
            name='haveExamClass',
            field=models.BooleanField(default=False, verbose_name='Экзаменационный класс'),
        ),
    ]
