# Generated by Django 4.2 on 2023-05-24 10:00

import django.core.validators
from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_code_department_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSGatewayToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('ref_token', models.TextField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VerifySMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='ИИН')),
                ('phone_number', mainapp.models.KazakhstanPhoneField(blank=True, max_length=12, null=True, verbose_name='Номер телефона')),
                ('code', models.CharField(verbose_name='code')),
            ],
        ),
    ]
