# Generated by Django 4.2 on 2023-05-15 05:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_auto_color_auto_category_auto_grnz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='category',
            field=models.CharField(max_length=8, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='transmission',
            field=models.CharField(choices=[('MT', 'Механика'), ('AT', 'АКПП'), ('NO', 'Другое')], default='AT', max_length=2, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 15)), django.core.validators.MaxValueValidator(datetime.date(2023, 5, 29))], verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='practiceexam',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 15)), django.core.validators.MaxValueValidator(datetime.date(2023, 5, 29))], verbose_name='Дата'),
        ),
    ]
