# Generated by Django 4.2 on 2023-05-25 11:51

from django.db import migrations
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_applicant_app_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='phone_number',
            field=mainapp.models.KazakhstanPhoneField(blank=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
    ]
