# Generated by Django 4.2 on 2023-05-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_smsgatewaytoken_verifysms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsgatewaytoken',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
