# Generated by Django 4.2 on 2023-05-26 03:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_applicant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceexam',
            name='transmission',
            field=models.CharField(choices=[('A', 'Явка'), ('B', 'Не явка'), ('С', 'Другое')], default='A', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 26)), django.core.validators.MaxValueValidator(datetime.date(2023, 6, 9))], verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='practiceexam',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 26)), django.core.validators.MaxValueValidator(datetime.date(2023, 6, 9))], verbose_name='Дата'),
        ),
    ]
