# Generated by Django 4.2 on 2023-05-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_smsgatewaytoken_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsgatewaytoken',
            old_name='ref_token',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='smsgatewaytoken',
            old_name='token',
            new_name='refresh_token',
        ),
    ]
