# Generated by Django 4.2 on 2023-05-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_practiceexam_transmission_alter_exam_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practiceexam',
            old_name='transmission',
            new_name='status',
        ),
    ]
