# Generated by Django 4.2 on 2023-05-17 10:35

import datetime
import django.core.validators
from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_exam_date_alter_practiceexam_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='phone_number',
            field=mainapp.models.KazakhstanPhoneField(blank=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 17)), django.core.validators.MaxValueValidator(datetime.date(2023, 5, 31))], verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='practiceexam',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 17)), django.core.validators.MaxValueValidator(datetime.date(2023, 5, 31))], verbose_name='Дата'),
        ),
    ]
