# Generated by Django 4.2 on 2023-05-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_ref_token_smsgatewaytoken_access_token_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SMSGatewayToken',
            new_name='GatewayToken',
        ),
    ]
