# Generated by Django 4.2 on 2023-05-29 05:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_transmission_practiceexam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=72, verbose_name='ЦОН'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 29)), django.core.validators.MaxValueValidator(datetime.date(2023, 6, 12))], verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='practiceexam',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 29)), django.core.validators.MaxValueValidator(datetime.date(2023, 6, 12))], verbose_name='Дата'),
        ),
    ]
