# Generated by Django 4.2 on 2023-05-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_smsgatewaytoken_gatewaytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Код Цона'),
        ),
    ]
