# Generated by Django 4.2 on 2023-05-29 05:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_department_name_alter_exam_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 29)), django.core.validators.MaxValueValidator(datetime.date(2024, 5, 28))], verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='practiceexam',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 29)), django.core.validators.MaxValueValidator(datetime.date(2024, 5, 28))], verbose_name='Дата'),
        ),
    ]
