# Generated by Django 4.2 on 2023-05-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='category',
            field=models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('A', 'A'), ('B', 'B'), ('C1', 'C1'), ('C', 'C'), ('D1', 'D1'), ('D', 'D'), ('BE', 'BE'), ('C1E', 'C1E'), ('CE', 'CE'), ('D1E', 'D1E'), ('DE', 'DE')], default='A1', max_length=3, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='transmission',
            field=models.CharField(choices=[('MT', 'Механика'), ('AT', 'АКПП')], default='AT', max_length=2, verbose_name='КПП'),
        ),
    ]
