# Generated by Django 4.2 on 2023-05-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(default='', max_length=126, verbose_name='Адрес местонахождения'),
        ),
    ]
